python3 infer_tri.py \
  --checkpoint /workspace/data/checkpoints/LCCNet/lg_innotek/consistency_loss/models/checkpoint_tri_e99_0.011.tar \
  --data-root /workspace/data/LG_Innotek/CustomDataset/lg_innotek \
  --dataset lg_innotek \
  --split val \
  --val-scenes afternoon_campus_2 \
  --val-frame-limit 32 \
  --batch-size 1 \
  --num-workers 8 \
  --use-sequence \
  --seq-len 4 \
  --seq-stride 1 \
  --use-recurrence \
  --recurrent-hidden-dim 256 \
  --max-r 20.0 \
  --max-t 1.0 \
  --output /workspace/data/checkpoints/LCCNet/lg_innotek/lg_innotek_tri/infer.json
